### ISSUE TITLE
web/intex.ts import ts files with .js path

### ISSUE THREAD

**Issue by Kcin1993** [tomoyanakano/shopify-app-template-node-typescript#1]
Hi, thank you for creating this template.

I noticed that the files imported in `web/index.ts` imported `.js` file, while the files in the directory, such as `shopify.ts`, `product-creator.ts`, and `gdpr.ts` all have a `.ts` extension. What is the reason for this?

Also, I noticed that if I remove the `.js` in the import path, it causes `web/index.ts` to fail to import the files properly.

Thank you again for creating the TypeScript version of this app.

**Comment by tomoyanakano** [comment]
Hi, thank you for your comment. 

Yes, as you mentioned it is required to add `.js` even though the file is `.ts`.
It is problem of `Tyepscript + Nodejs ESM`.

**Related Issues**
https://github.com/TypeStrong/ts-node/issues/1777
https://stackoverflow.com/questions/63742790/unable-to-import-esm-ts-module-in-node

I think it could be solved now, I'll try it.
Thank you for reporting.

**Comment by Kcin1993** [comment]
Thanks for your information 👍
